### ISSUE TITLE
ReferenceError on  Example menu

### ISSUE THREAD

**Issue by insanehong** [summernote/summernote.github.io#13]
![image](https://cloud.githubusercontent.com/assets/1558742/8680185/8ca81a3c-2a9a-11e5-8117-0f9f23afe893.png)

Sorry ,This issue from #12.

I will send patch for this issue ASAP.

**Comment by insanehong** [comment]
PR #14

**Comment by hackerwins** [comment]
@insanehong Thanks :+1:
