### ISSUE TITLE
Modules example 404

### ISSUE THREAD

**Issue by gorjan-mishevski** [summernote/summernote.github.io#31]
Hi!
This part: For more module examples: modules
points to this link: https://github.com/summernote/summernote/tree/develop/src/js/bs3/module
which is 404.

**Comment by DiemenDesign** [comment]
@hackerwins, the folder the link points to no longer exists, where do you want it to point too?

**Comment by lqez** [comment]
Thank you for reporting! Fixed by https://github.com/summernote/summernote.github.io/pull/32
