### ISSUE TITLE
insert element in current position

### ISSUE THREAD

**Issue by sadeghi4j** [summernote/summernote.github.io#34]
the insertText and insertNode should insert element in caret current position by default.
And there is a poor documentation about all api.

**Comment by lqez** [comment]
Thank you for using Summernote. Could you make a pull request for updating docs?

**Comment by DiemenDesign** [comment]
@sadeghi4j do you have an example of how you think the documentation should be worded, I would be more than happy to do a PR to change what is currently there, especially if it makes the explanation clearer for others. Thank you.
