### ISSUE TITLE
add static version of documentation?

### ISSUE THREAD

**Issue by blairanderson** [summernote/summernote.github.io#4]
When you search google for ["summernote onpaste"](https://www.google.com/search?q=summernote+onpaste) i would expect summernote.org docs to show up first. 

Any benefits of angular instead of regular static site generator other than angular documentation being neat?

i'm happy to help if you want to change directions

**Comment by hackerwins** [comment]
@blairanderson Thanks for reporting.
We have decided to change angularjs with jekyll(https://jekyllrb.com/) after v0.7.0.
https://github.com/summernote/summernote.github.io/tree/v0.7.0
If you have any idea about documentation or SEO, please let me know.

Thanks
