### ISSUE TITLE
Add recently added feature / options

### ISSUE THREAD

**Issue by lqez** [summernote/summernote.github.io#41]

**Comment by lqez** [comment]
https://github.com/summernote/summernote/pull/3310

**Comment by lqez** [comment]
https://github.com/summernote/summernote/pull/3319

**Comment by lqez** [comment]
https://github.com/summernote/summernote/pull/3310

**Comment by DiemenDesign** [comment]
Have these already been added to the Docs @lqez ? Or does the descriptions need updating?
#3310 https://summernote.org/deep-dive/#custom-fontnames
#3319 https://summernote.org/deep-dive/#custom-placeholder

**Comment by lqez** [comment]
@DiemenDesign #3310 introduces `addDefaultFonts`, not custom fontnames and #3319 is for `inheritPlaceholder`, not just custom placeholder.

**Comment by DiemenDesign** [comment]
Do the docs need updating for those?

**Comment by lqez** [comment]
@DiemenDesign Yeap, I think so. At least we have to describe entire options in `settings.js`

**Comment by DiemenDesign** [comment]
Agreed, there have been many questions asking what things do. The last PR/Merge I did sort the options Alphabetically to make it easier to find things.

**Comment by DiemenDesign** [comment]
I've added in WIP placeholder in the Deep Dive page for the missing Callbacks. I'm not sure exactly what these Callbacks do, so I was hoping this might encourage someone or one of the other Developers to edit or let us know.
