### ISSUE TITLE
Please add a hint how to intregrate with JQuery.Validation and JQuery Validation Unobstrusive

### ISSUE THREAD

**Issue by Bjego** [summernote/summernote.github.io#42]
Hey,
when you use summernote together with Jquery Validation you might get some validation issues on the client. This can get fixed, if the programmer updates the jquery validation default ignores:

```
// This will set `ignore` for all validation calls
jQuery.validator.setDefaults({
  // This will ignore all hidden elements alongside `contenteditable` elements
  // that have no `name` attribute
  ignore: ":hidden, [contenteditable='true']:not([name])"
});
```

When you google around you will see that this is a common issue and lots of guys use hardcoded Ids to handle this issue.

See this discussion here: 
https://github.com/jquery-validation/jquery-validation/issues/1875

And this stackoverflow thread:
https://stackoverflow.com/questions/42086841/jquery-validate-with-summernote-editor-error-cannot-read-property-replace-of/58092791#58092791

**Comment by DiemenDesign** [comment]
This is something more to do with jquery-validation than it is with Summernote. As with other projects like elfinder (as an example), they keep and maintain how to integrate their project with others, not the other way around. As you would imagine not everyone uses the same projects, if we did it for this one, we would need to do it for all of them.
