### ISSUE TITLE
Build preview sites for pull requests

### ISSUE THREAD

**Issue by lqez** [summernote/summernote.github.io#54]

**Comment by easylogic** [comment]
can you make ${pr_id}.summernote.org  domain ?

**Comment by DiemenDesign** [comment]
Can we have numbers for a subdomain? If not maybe something like pr345.summernote.org, or would it be easier just to have it as a folder like summernote.org/pr345

**Comment by lqez** [comment]
I think Netlify can do it - example) https://deploy-preview-57--muchtrans.netlify.com/

**Comment by easylogic** [comment]
@lqez good idea!!

**Comment by lqez** [comment]
Working on it

**Comment by lqez** [comment]
Done
