### ISSUE TITLE
Loading HTML into Summernote

### ISSUE THREAD

**Issue by kmaiwand** [summernote/summernote.github.io#59]
To make the summernote content persistent, I save it in a DB. When I load the content back (using insertText), summernote shows the HTML code rather than interpret/render it. How do I save and load the summernote content?

**Comment by DiemenDesign** [comment]
Load the content into the editable area before initialising Summernote. If using a form with a `<textarea/>` element, you would put the data in the `<textarea/>` before initialising Summernote.
Or use the `pasteHTML` function from the Summernote API https://summernote.org/deep-dive/#pastehtml

**Comment by lqez** [comment]
This repository contains the homepage of Summernote, not Summernote editor itself.
If you have any question on Summernote, please leave it on https://github.com/summernote/summernote.
Thanks.
