### ISSUE TITLE
Fail download on main page

### ISSUE THREAD

**Issue by dc7303** [summernote/summernote.github.io#63]
![image](https://user-images.githubusercontent.com/40932237/88549285-10c26c80-d05b-11ea-963a-e61a657851b8.png)

I clicked the download button on the main page, but 404 Not Found occurs.

**Comment by dc7303** [comment]
The moved link is `https://codeload.github.com/summernote/summernote/zip/master`

**Comment by DiemenDesign** [comment]
This has since been resolved.
