### ISSUE TITLE
Vulnerability issue

### ISSUE THREAD

**Issue by RajanDhinoja** [summernote/summernote.github.io#67]
There is a vulnerability issue in the plugin. snyk throwing the vulnerability issue.

**Comment by DiemenDesign** [comment]
Shouldn't you opening an issue such as this on the project page? This repository is for the Website for Summernote.
Also, if you have found a vulnerability, you should explain concisely what you found, any errors that are thrown in console, and where you think the vulnerability is with the project, just stating that "snyk" (whatever that is) does not tell us enough to look into what your reporting.

**Comment by RajanDhinoja** [comment]
@DiemenDesign you can check this out 
https://snyk.io/vuln/SNYK-JS-SUMMERNOTE-597187

**Comment by DiemenDesign** [comment]
We are already aware, and if you had of gone to the main repository, and looked at the issues, and Pull Requests you would have seen as such.
