### ISSUE TITLE
It ain't working...

### ISSUE THREAD

**Issue by TimOgilvy** [summernote/summernote.github.io#7]
Hello folks,

This path (summernote.github.io) now redirects to summernote.org, where all the links are broken and redirect to the front page.

It looks like a broken .htaccess redirect, as you can make up any URL and it all gets appended with a hash.

eg:
http://summernote.org/somethingimadeup.html 
becomes
http://summernote.org/somethingimadeup.html#/ 

Cheers

**Comment by insanehong** [comment]
I think, This problem caused by using angular router.

**Comment by insanehong** [comment]
Why not use [angular-ui-router](https://github.com/angular-ui/ui-router) ? It's supported ui-sref directive that will automatically generate  href attribute via route state https://github.com/angular-ui/ui-router/wiki/Quick-Reference#ui-sref
