### ISSUE TITLE
Enable backspace key?

### ISSUE THREAD

**Issue by malerba423** [summernote/summernote.github.io#71]
I am unable to use the backspace and delete keys in the summernote editors that I have integrated into my site. 

I understand that this is probably by design, and in fact a little poking around the repo has revealed some code that seems to confirm that suspicion, but I can't find any documentation on how to configure summernote to enable deleting text and/or images. 

Currently I am unable to delete anything (text, pictures, videos, etc) once it's been inserted and it makes for a really lousy user experience.

**Comment by DiemenDesign** [comment]
I just checked on several resources to see if instances I use, and even https://summernote.org/ site, and backspace, and delete work as I would expect them to.

It's possible there is another script interfering, possibly even a Summernote Plugin if you are using one or more, which could be causing your issues.

Also, I normally leave issues open when the issue template has been ignored and removed. The template may seem like a waste of time to you, but for us, it helps us diagnose what's going on with your issue. For e.g. knowing what Browser/s, and Operating System/s, and version of Summernote your using.

**Comment by malerba423** [comment]
@DiemenDesign thanks for the reply. 

Firstly, yeah, other instances of summernote that I've seen elsewhere seem to have a normal/functional backspace key. I'm unsure what would be interfering with mine, but noted. I'll try standing one up in a totally standalone page and see if maybe it works like that...

Secondly, I didn't scrap/ignore the issue template, there simply *was* no template. I used the "New Issue" button on [this page here](https://github.com/summernote/summernote.github.io/issues). Maybe y'all need to make that button pull from a template?

**Comment by DiemenDesign** [comment]
lol, I didn't even notice that you've opened the issue on the Website repository, not the actual repository of Summernote where it should have been opened, oh well.

**Comment by malerba423** [comment]
@DiemenDesign originally I almost posted an issue in the actual summernote repo, but I actually read the template that you are referring to, and it told me that if I had an issue with the documentation instead of the actual code that I should open an issue here. So that's what I tried instead. 

Aaaaanyway, your first instinct was correct. We had a universal keydown listener that was blocking the event. Apologies / sorry for the trouble / thanks for the help!

Cheers
Joel

**Comment by DiemenDesign** [comment]
All good, glad you found the issue.
